In [ ]:
import pandas as pd
import numpy as np
import h5py

path = 'data/ca_his_raw_2019.h5'
with h5py.File(path, "r") as f:
    print(list(f.keys()))
    def show(name, obj):
        if isinstance(obj, h5py.Dataset):
            print(name, obj.shape, obj.dtype)

    f.visititems(show)

['t']
t/axis0 (8600,) |S9
t/axis1 (105120,) int64
t/block0_items (8600,) |S9
t/block0_values (105120, 8600) float64

In [147]:
domain = pd.read_csv('data/ca_meta.csv', dtype={"ID": str})
domain.head()

,ID,Lat,Lng,District,County,Fwy,Lanes,Type,Direction,ID2
0,317802,38.389811,-121.479587,3,Sacramento,I5-N,2,Mainline,N,0
1,312134,38.412564,-121.484319,3,Sacramento,I5-N,2,Mainline,N,1
2,312133,38.428630,-121.487657,3,Sacramento,I5-N,3,Mainline,N,2
3,313159,38.450246,-121.492176,3,Sacramento,I5-N,3,Mainline,N,3
4,319767,38.465539,-121.496450,3,Sacramento,I5-N,3,Mainline,N,4

In [148]:
domain_fwy = ['SR22-E','SR22-W','SR55-N','SR55-S']
if (domain['Fwy'].isin(domain_fwy)).any():
        print(domain['ID'].to_string(index=False).replace(r'   ', '').split('\n'))

['317802', '312134', '312133', '313159', '319767', '319780', '317830', '314876', '314886', '314909', '314780', '314936', '314792', '314848', '316074', '316073', '314808', '314955', '314982', '315017', '314821', '318632', '319306', '315054', '315969', '315927', '317843', '317806', '312132', '315060', '314652', '319805', '319793', '317835', '314877', '318599', '314786', '318626', '314799', '314853', '318484', '318674', '314828', '315030', '319314', '315042', '314994', '315006', '318249', '318259', '315938', '315955', '318721', '318711', '317842', '313824', '318383', '318451', '313840', '311974', '312139', '318282', '312098', '313728', '314270', '313671', '313684', '319212', '313698', '314371', '319334', '314559', '313938', '319644', '319631', '313753', '313897', '313852', '314711', '314668', '313765', '313867', '313658', '314536', '319043', '319046', '314042', '314036', '313631', '313912', '313618', '313055', '316271', '318551', '313606', '313551', '313552', '316949', '315105', '314379', '314248', '316959', '316648', '319467', '316654', '320015', '316666', '316682', '316888', '316690', '316699', '316708', '318467', '316716', '316898', '308511', '320287', '320280', '317706', '317715', '317722', '317743', '317736', '318354', '318366', '313772', '313835', '312010', '312103', '312236', '312205', '313931', '312264', '313000', '313747', '313890', '313846', '313003', '313005', '313790', '313861', '318961', '313010', '313652', '313035', '313037', '314059', '313625', '313904', '313612', '313080', '313082', '316279', '313339', '313601', '313344', '313349', '316970', '315098', '314241', '314230', '316964', '316653', '319457', '316661', '320002', '316670', '316678', '316894', '316694', '316704', '316712', '318458', '316720', '316902', '308512', '320290', '320282', '317704', '317716', '317723', '317742', '317735', '313956', '312689', '312694', '312745', '313951', '314121', '312865', '314147', '312858', '312782', '312804', '312807', '312895', '312896', '312898', '312940', '312944', '316114', '313184', '318586', '  3070033', '  3070013', '312854', '312856', '312857', '312757', '312771', '314157', '318540', '313197', '313204', '314598', '316129', '312900', '319268', '312942', '312946', '318593', '  3075061', '316593', '319110', '316601', '318401', '318421', '316617', '320045', '317081', '  3048041', '319252', '319032', '  3075081', '314724', '317098', '316597', '319129', '319119', '316605', '318412', '318432', '316621', '320036', '317088', '  3048042', '319239', '319036', '318113', '316773', '318017', '314013', '314025', '316783', '318067', '318076', '  3052091', '318053', '316803', '314548', '318135', '316817', '317884', '  3044021', '315804', '320442', '320457', '320628', '320630', '316143', '316140', '312343', '312439', '316166', '313111', '313114', '317853', '313132', '316084', '315993', '316009', '316019', '316018', '316045', '316063', '314514', '313376', '316328', '316314', '313393', '313406', '314460', '314446', '313420', '313432', '313567', '313444', '  3052053', '313456', '313469', '313475', '319351', '316414', '318620', '318927', '318650', '318801', '318844', '318764', '317002', '317008', '317752', '317018', '316733', '316743', '316760', '316753', '316204', '316214', '316249', '317797', '317791', '319415', '319673', '314277', '318102', '313979', '316788', '318068', '318077', '316808', '318126', '318142', '316822', '  3044012', '317885', '319142', '320449', '320429', '320616', '312326', '312346', '316160', '320563', '320483', '320644', '317852', '316174', '316085', '316001', '315982', '316032', '313487', '314165', '313368', '314491', '314485', '313386', '313405', '314433', '314419', '313426', '313414', '313560', '313438', '313450', '313468', '313482', '313493', '313512', '318612', '318934', '316438', '316451', '318950', '318816', '318773', '318788', '319388', '314217', '317013', '317157', '317166', '317023', '316738', '316748', '316768', '316758', '316206', '316222', '316252', '317798', '317789', '318688', '319674', '317147', '319091', '317146', '317143', '317862', '319390', '319481', '314730', '313190', '314697', '314698', '313166', '313172', '313178', '317960', '317948', '312648', '312651', '312233', '312382', '312386', '312388', '317910', '312421', '312422', '312425', '312513', '312514', '312520', '312523', '312525', '312527', '  3070092', '312562', '318566', '312566', '  3044091', '316827', '316835', '  3050081', '316851', '316862', '317038', '316922', '316932', '316940', '319100', '317141', '317139', '317861', '317869', '314689', '317934', '314625', '312570', '316399', '314681', '314617', '314501', '319075', '317903', '312420', '317974', '  3046032', '318029', '312517', '  3070073', '318035', '313144', '317896', '  3070083', '318859', '312564', '  3070053', '317045', '  3044101', '320552', '316839', '  3050101', '316856', '316916', '317042', '316928', '316936', '316944', '404356', '402518', '402516', '402214', '402212', '402210', '402835', '414294', '414295', '402513', '414025', '402512', '402510', '414028', '416736', '414031', '402837', '401952', '414032', '406623', '405046', '414039', '405270', '402207', '405580', '414480', '400615', '402205', '401568', '400049', '406056', '407233', '406057', '405269', '400764', '400270', '404350', '401485', '400324', '404873', '414035', '402503', '402203', '401826', '401828', '401829', '402502', '414041', '401954', '402069', '408154', '408602', '408604', '409956', '409958', '409960', '416929', '402491', '416930', '416449', '414707', '402489', '414831', '414830', '414829', '421970', '405742', '402482', '402086', '423158', '402088', '402090', '402091', '402094', '402096', '408152', '408151', '408606', '424094', '424095', '424096', '424092', '424091', '424098', '402522', '403267', '402521', '406065', '402517', '402505', '402515', '402213', '402211', '402209', '414046', '402834', '402514', '414306', '402511', '402509', '414050', '402507', '414056', '402836', '402208', '401951', '414053', '405583', '401756', '414060', '414311', '402206', '405585', '414058', '400516', '402204', '401476', '400993', '406063', '407238', '406064', '405274', '405276', '405275', '402504', '404358', '401526', '404360', '414043', '404877', '414057', '401825', '401827', '402501', '401830', '408164', '402068', '408165', '408615', '411075', '409966', '409968', '416940', '402490', '416943', '416459', '414719', '402488', '414839', '414840', '414838', '414837', '421977', '402483', '405746', '402085', '402089', '402087', '402092', '402093', '402095', '408166', '402098', '408619', '424105', '424106', '424104', '424111', '424110', '406788', '406789', '406790', '406791', '406792', '421688', '409478', '409479', '409480', '409481', '420469', '406793', '406794', '406795', '406796', '407239', '403471', '404365', '400108', '400154', '405279', '400649', '400715', '400240', '403329', '400436', '400221', '404370', '403475', '405586', '400416', '405281', '404378', '400832', '400073', '400278', '400298', '400100', '403280', '400655', '401381', '400103', '402202', '402479', '407990', '404381', '407992', '407987', '400048', '401687', '400736', '400438', '400345', '400389', '401681', '401746', '400323', '400171', '400579', '400532', '402476', '400251', '400197', '400494', '401684', '401002', '400946', '400748', '401390', '400406', '400224', '404668', '400083', '402480', '402201', '402481', '402200', '407995', '404385', '408000', '407997', '400989', '400101', '400617', '400413', '401689', '400747', '400354', '401683', '400800', '400600', '400616', '400619', '401423', '400550', '400878', '400289', '401692', '400604', '400580', '401482', '403744', '401674', '401679', '401677', '401682', '401680', '401666', '401678', '422007', '402039', '402041', '402043', '402045', '402047', '401706', '401702', '401696', '401694', '401701', '402049', '402051', '422009', '402038', '402040', '402042', '402044', '402046', '401704', '401703', '401693', '401700', '401699', '402048', '402050', '402814', '402815', '402816', '402817', '420340', '404896', '404921', '404886', '404923', '404885', '404906', '404891', '404908', '404889', '404910', '404892', '404912', '404894', '404914', '404897', '404898', '404899', '401546', '404400', '401892', '401657', '401671', '405450', '403430', '401513', '403998', '405589', '400679', '401198', '400432', '400728', '400612', '408632', '401079', '415253', '401901', '401239', '402062', '400329', '401509', '401575', '401195', '400027', '401558', '401045', '400182', '400445', '400443', '401221', '405754', '401228', '406652', '400770', '401895', '417277', '416790', '401243', '401551', '401209', '401260', '400082', '400976', '400838', '400430', '400865', '400902', '401269', '400660', '401070', '401058', '415255', '401090', '415254', '400478', '403946', '403276', '403458', '400124', '403460', '408634', '401793', '404401', '423339', '407865', '400829', '400622', '402174', '408178', '404388', '409100', '423336', '404390', '407869', '402079', '407866', '410772', '402239', '411793', '402235', '410778', '402002', '410774', '410775', '410776', '413094', '410741', '413371', '401318', '410756', '422791', '401781', '401784', '401787', '401789', '413372', '401791', '410745', '404391', '401151', '402004', '401879', '412683', '410742', '411792', '413373', '403455', '413374', '413375', '412684', '411113', '410764', '413380', '413377', '401878', '413376', '411118', '409998', '410761', '413091', '408464', '410752', '410767', '408784', '410750', '410755', '411116', '402241', '402243', '402245', '402246', '403425', '402248', '402250', '402251', '402255', '402257', '402259', '402261', '402263', '402264', '402266', '402268', '402270', '421492', '402827', '414758', '404918', '404920', '404883', '404922', '404884', '404905', '404887', '404907', '404888', '404909', '404890', '404911', '404893', '404913', '404895', '404915', '404916', '404917', '404415', '404416', '401503', '407750', '401539', '401698', '401211', '405602', '400691', '400126', '401242', '400009', '400176', '400060', '401524', '401066', '401900', '401234', '401052', '409584', '400628', '400079', '400755', '401229', '400470', '400819', '401041', '400378', '400113', '400361', '401253', '405763', '415263', '401256', '406660', '401894', '417288', '416774', '401197', '401571', '401215', '411149', '400411', '400538', '400465', '400929', '401480', '400313', '401230', '400301', '401084', '401081', '401083', '401226', '415264', '400707', '401274', '400235', '403459', '400501', '403461', '401673', '401395', '404407', '401646', '401636', '401638', '400337', '400128', '404745', '404408', '409107', '400074', '404409', '404410', '407883', '402077', '414093', '422019', '402238', '411804', '402234', '410820', '410824', '410825', '410826', '410829', '401219', '410790', '421744', '422796', '401216', '421006', '401782', '401785', '401786', '401788', '413389', '401790', '410791', '410782', '404413', '402003', '401152', '401155', '412696', '410779', '411131', '411132', '410803', '411134', '411137', '409232', '410817', '410814', '401877', '413390', '410811', '408790', '410808', '410805', '408473', '410788', '401923', '410786', '411141', '411140', '402240', '402242', '402244', '403426', '402247', '402249', '402252', '402253', '402254', '402256', '402258', '402260', '402262', '402265', '402267', '402269', '421503', '400729', '404439', '401880', '400410', '413716', '400132', '400444', '400145', '400268', '401555', '400052', '400461', '400750', '400148', '400336', '400713', '400485', '400822', '400464', '400688', '404434', '400222', '400952', '401210', '400507', '400185', '400677', '404435', '407344', '407321', '407331', '407341', '407339', '407337', '402060', '407336', '407335', '407328', '407342', '407325', '407323', '400174', '404442', '404448', '400963', '400894', '400577', '400754', '400519', '400637', '400085', '400690', '400059', '400717', '400772', '400700', '400017', '400934', '400792', '400907', '400213', '404444', '400582', '400097', '401224', '400828', '400648', '400209', '407370', '407373', '407372', '407364', '402061', '407361', '407360', '407352', '407367', '407348', '400528', '407374', '400869', '400149', '401937', '405613', '400280', '401129', '401957', '404451', '400178', '401567', '404452', '401597', '400418', '400654', '400664', '404453', '400258', '400916', '400563', '402056', '402059', '402118', '409524', '409525', '409526', '401817', '400842', '401154', '401958', '404462', '400457', '401457', '405619', '401606', '400257', '400040', '400837', '404461', '400995', '400065', '400236', '402057', '402058', '402117', '409528', '409529', '401816', '401547', '417374', '401453', '401012', '401426', '421771', '400861', '400314', '401053', '409614', '401402', '401343', '400683', '406688', '406685', '406695', '401223', '417405', '405644', '400504', '401431', '421793', '400905', '400162', '401065', '409635', '401298', '401394', '401305', '400071', '406713', '406716', '406719', '409868', '402294', '409869', '402296', '409870', '402298', '402008', '409893', '402300', '409858', '402302', '409865', '402011', '409889', '409884', '414192', '409892', '410112', '409878', '409881', '409873', '402314', '409872', '410515', '410106', '421640', '401592', '409856', '402321', '410108', '409859', '409880', '402327', '409877', '402328', '411233', '413786', '401581', '401578', '401586', '410099', '401660', '401663', '410096', '402337', '402339', '410097', '402341', '410098', '407429', '401662', '402343', '401670', '410100', '400237', '402345', '401658', '410083', '410084', '402347', '400181', '400014', '402350', '400474', '404519', '402353', '400858', '413782', '402355', '400325', '400591', '402356', '402358', '413205', '400195', '402359', '401908', '400804', '402361', '400400', '401890', '400996', '400668', '402362', '400965', '400001', '404753', '402364', '400863', '400911', '400760', '400964', '400227', '404521', '400353', '401994', '400246', '402366', '400168', '400790', '402370', '401996', '401997', '404522', '401998', '402372', '401534', '401948', '401507', '401949', '402376', '402377', '402379', '402380', '404529', '422116', '400859', '404533', '400981', '402398', '404534', '401474', '400388', '401927', '401653', '401872', '405673', '401874', '405679', '401835', '404531', '404532', '401834', '401833', '401929', '401652', '401882', '401832', '401869', '401859', '401910', '401443', '402383', '401914', '400661', '400291', '400107', '400645', '405859', '402385', '402387', '405827', '402389', '405848', '403261', '400753', '400720', '401199', '400935', '400527', '400007', '400817', '400420', '400797', '400381', '400441', '403258', '401336', '400119', '401411', '400975', '413195', '400593', '400125', '400331', '400010', '400473', '400039', '400316', '400503', '400540', '405843', '408093', '402390', '401448', '402391', '400497', '405841', '404520', '400183', '401469', '401472', '405838', '400260', '404528', '401795', '401358', '400255', '401934', '401277', '400868', '401409', '401516', '406871', '401819', '409306', '402553', '402555', '402557', '402559', '402561', '402563', '402565', '402567', '402569', '402571', '402573', '402575', '402577', '402579', '402581', '402583', '402585', '401624', '402587', '402140', '402141', '402142', '403317', '403315', '403313', '402589', '402591', '402593', '402595', '402597', '402599', '402601', '400656', '400428', '400630', '400598', '400283', '400349', '400962', '401616', '400768', '400214', '400390', '405367', '405369', '405386', '402607', '405373', '405374', '402609', '402612', '405377', '405384', '402613', '402615', '402617', '402619', '402621', '412392', '402623', '402631', '402633', '415657', '415667', '421929', '415649', '406287', '406289', '402639', '402641', '402643', '402645', '406551', '412398', '412395', '402649', '416587', '402651', '406553', '402655', '402657', '406554', '402659', '402661', '406556', '409663', '406557', '402663', '409664', '402665', '409666', '406558', '402667', '406562', '406564', '401758', '401605', '420141', '402671', '401598', '402673', '402675', '401603', '401602', '402677', '402125', '402128', '402129', '402132', '402133', '402135', '402138', '409674', '410502', '409671', '409673', '409668', '409683', '410505', '409678', '409681', '410504', '402698', '402701', '402703', '402704', '402706', '402708', '402710', '402712', '402713', '403270', '402717', '402719', '402721', '402723', '402725', '402727', '402729', '403271', '402734', '402736', '402739', '402753', '402742', '402744', '402746', '402748', '402602', '402751', '402754', '402756', '402758', '402760', '402765', '402767', '402604', '402769', '402763', '406742', '402773', '402775', '402777', '402779', '409926', '402295', '409927', '402297', '409928', '402299', '408716', '409933', '402301', '409919', '402303', '409935', '402010', '402106', '401691', '414227', '409948', '410167', '409943', '409924', '409931', '410563', '410163', '409462', '421675', '401589', '409918', '402322', '410165', '409929', '409941', '409940', '402329', '409938', '409942', '409946', '401579', '410157', '410153', '410155', '401668', '410150', '402338', '402340', '410151', '402342', '410152', '407439', '402344', '401661', '410158', '400223', '410169', '402346', '401669', '410142', '410143', '402348', '401881', '404547', '402349', '402351', '400742', '402352', '400978', '406151', '413820', '400891', '413814', '402357', '400138', '416623', '402360', '401906', '401891', '400160', '400440', '402363', '400109', '400922', '400394', '402365', '400172', '400586', '400895', '400206', '400372', '400069', '402367', '400794', '400643', '400904', '404553', '402371', '400330', '400743', '400545', '400435', '402373', '401936', '401926', '400264', '402000', '402378', '404561', '404563', '402381', '404558', '422161', '400425', '400733', '404559', '402122', '400578', '404560', '401467', '400783', '401913', '401649', '401873', '404572', '401875', '401837', '401876', '404573', '404574', '401860', '401861', '401928', '401651', '401883', '401868', '401870', '401831', '402382', '402384', '401439', '401446', '400272', '400531', '400884', '407007', '402386', '402388', '405877', '403262', '400263', '400730', '401233', '400002', '400106', '400621', '401000', '400787', '400098', '400421', '400439', '403259', '401634', '401631', '400568', '400657', '401515', '400784', '400484', '400977', '400340', '400116', '400763', '400886', '406032', '400766', '401523', '408101', '401451', '408098', '402392', '400781', '405900', '404575', '400744', '401462', '401501', '405870', '400641', '404569', '401454', '401357', '401935', '401285', '400043', '401410', '401408', '401405', '401820', '409335', '402554', '402556', '402558', '402560', '402562', '402564', '402566', '402568', '402570', '402572', '402574', '402576', '402578', '402580', '402582', '402584', '400547', '402586', '402588', '402139', '403316', '403314', '416911', '403312', '402590', '402592', '402594', '402596', '402598', '402600', '400382', '400011', '400525', '400782', '400460', '400727', '400392', '400620', '400304', '400143', '400513', '400000', '405389', '402605', '402606', '405390', '405406', '402608', '405395', '405398', '402610', '402611', '405399', '405394', '402614', '402616', '402618', '402620', '402622', '412439', '402624', '402632', '402634', '415697', '415704', '421965', '402005', '406302', '406305', '402640', '402642', '402644', '402646', '406573', '412443', '412446', '402650', '416620', '402652', '406575', '403303', '402658', '406577', '402660', '402662', '406578', '409712', '406579', '402664', '409715', '402666', '409717', '406586', '402668', '401766', '401728', '418244', '401595', '401601', '402672', '401604', '402674', '402676', '401599', '401609', '402124', '402126', '402127', '402130', '402131', '402134', '402136', '402137', '409720', '409722', '409724', '409733', '409725', '410553', '410547', '409728', '409730', '410550', '402702', '410545', '402705', '402707', '402709', '402711', '402714', '402716', '402718', '402720', '402722', '402724', '402726', '402728', '402730', '402731', '402733', '402735', '402737', '402738', '402740', '402741', '402743', '402745', '402747', '402749', '402603', '402752', '4

In [152]:
domain_fwy = ['SR22-E','SR22-W','SR55-N','SR55-S']
domain.loc[domain['Fwy'].isin(domain_fwy), 'ID'].to_string(index=False).split('\n')

['1202590',
 '1214853',
 '1215236',
 '1202595',
 '1214869',
 '1202614',
 '1215092',
 '1202627',
 '1202648',
 '1202691',
 '1214938',
 '1214955',
 '1202705',
 '1202720',
 '1202742',
 '1202753',
 '1214988',
 '1215003',
 '1214805',
 '1202779',
 '1202785',
 '1215252',
 '1214894',
 '1202827',
 '1215017',
 '1202844',
 '1202855',
 '1215043',
 '1202885',
 '1214715',
 '1202901',
 '1212170',
 '1202921',
 '1202949',
 '1202964',
 '1202977',
 '1214881',
 '1215026',
 '1202574',
 '1202564',
 '1214854',
 '1215248',
 '1202599',
 '1214871',
 '1202610',
 '1215091',
 '1202631',
 '1202663',
 '1202676',
 '1214939',
 '1214954',
 '1202701',
 '1202724',
 '1202738',
 '1214972',
 '1214987',
 '1215002',
 '1214806',
 '1202766',
 '1202789',
 '1215250',
 '1202803',
 '1202814',
 '1215018',
 '1202840',
 '1202859',
 '1215044',
 '1202872',
 '1211641',
 '1202912',
 '1202929',
 '1202917',
 '1202938',
 '1202960',
 '1202981',
 '1214882',
 '1202993',
 '1203021',
 '1203035',
 '1203057',
 '1203071',
 '1203082',
 '1210205',
 '1210190',
 '1210172',
 '1203090',
 '1214373',
 '1214321',
 '1203124',
 '1203148',
 '1203172',
 '1203184',
 '1214253',
 '1203221',
 '1203254',
 '1209860',
 '1209873',
 '1209888',
 '1203303',
 '1203331',
 '1203342',
 '1215811',
 '1212938',
 '1203400',
 '1212842',
 '1212863',
 '1203428',
 '1212916',
 '1212901',
 '1212955',
 '1203468',
 '1203016',
 '1203040',
 '1203050',
 '1203076',
 '1210220',
 '1203084',
 '1210189',
 '1210173',
 '1203095',
 '1214322',
 '1203110',
 '1203136',
 '1218332',
 '1203188',
 '1214215',
 '1203206',
 '1203239',
 '1203266',
 '1203271',
 '1203317',
 '1215809',
 '1212935',
 '1203361',
 '1203387',
 '1212840',
 '1212865',
 '1213274',
 '1212903',
 '1212957',
 '1203440']

In [153]:
def extract_details(fwy):
    with h5py.File(path, "r") as f:
        id = domain.loc[domain['Fwy'].isin(domain_fwy), 'ID'].to_string(index=False).split('\n')
        sensors_raw = [x.decode("utf-8") for x in f["t/axis0"][:]]
        sensors = []
        for i in sensors_raw:
            if i in id:
                sensors.append(i)
        timestamps = pd.to_datetime(f['t/axis1'][:])

        print('number of sensors:', len(sensors))
        print('first sensors:', sensors[:20])
        print('first timestamps:', timestamps[:5])
        return sensors, len(sensors), timestamps

domain_fwy = ['SR22-E','SR22-W','SR55-N','SR55-S']
domain_sensors, len_of_sensors, timestamps = extract_details(domain_fwy)

number of sensors: 141
first sensors: ['1202590', '1214853', '1215236', '1202595', '1214869', '1202614', '1215092', '1202627', '1202648', '1202691', '1214938', '1214955', '1202705', '1202720', '1202742', '1202753', '1214988', '1215003', '1214805', '1202779']
first timestamps: DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 00:05:00',
               '2019-01-01 00:10:00', '2019-01-01 00:15:00',
               '2019-01-01 00:20:00'],
              dtype='datetime64[ns]', freq=None)

In [189]:
def get_df(domain_sensors, len_of_sensors, timestamps, span):
    with h5py.File(path, "r") as f:
        values = f['t/block0_values'][:, :len_of_sensors]
    df = pd.DataFrame(values, index=timestamps, columns=domain_sensors[:len_of_sensors])
    if span == 1:
        df = df.loc['2019-01-01':'2019-06-30']
    elif span == 2:
        df = df.loc['2019-07-01':'2019-12-31']
    else:
        df = df
    return df
domain_df = get_df(domain_sensors, len_of_sensors, timestamps, 3)
domain_df

,1202590,1214853,1215236,1202595,1214869,1202614,1215092,1202627,1202648,1202691,...,1215809,1212935,1203361,1203387,1212840,1212865,1213274,1212903,1212957,1203440
2019-01-01 00:00:00,15.0,15.0,56.0,56.0,56.0,72.0,56.0,56.0,56.0,56.0,...,72.0,72.0,72.0,95.0,95.0,72.0,72.0,56.0,71.0,72.0
2019-01-01 00:05:00,16.0,16.0,57.0,57.0,57.0,72.0,57.0,57.0,57.0,57.0,...,72.0,72.0,72.0,93.0,93.0,72.0,72.0,57.0,71.0,72.0
2019-01-01 00:10:00,16.0,16.0,57.0,57.0,57.0,72.0,57.0,57.0,57.0,57.0,...,72.0,72.0,72.0,92.0,92.0,72.0,72.0,57.0,71.0,72.0
2019-01-01 00:15:00,40.0,28.0,43.0,66.0,68.0,80.0,98.0,70.0,75.0,104.0,...,86.0,92.0,55.0,86.0,161.0,87.0,78.0,91.0,79.0,83.0
2019-01-01 00:20:00,42.0,14.0,31.0,40.0,48.0,81.0,90.0,68.0,77.0,95.0,...,136.0,110.0,76.0,128.0,198.0,125.0,118.0,119.0,130.0,132.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-31 23:35:00,66.0,22.0,40.0,65.0,48.0,64.0,77.0,58.0,60.0,81.0,...,108.0,105.0,87.0,108.0,163.0,95.0,84.0,94.0,99.0,97.0
2019-12-31 23:40:00,58.0,24.0,27.0,50.0,41.0,55.0,74.0,46.0,51.0,68.0,...,99.0,88.0,79.0,98.0,166.0,91.0,76.0,93.0,73.0,73.0
2019-12-31 23:45:00,57.0,27.0,34.0,59.0,48.0,49.0,71.0,46.0,46.0,53.0,...,95.0,88.0,71.0,84.0,147.0,73.0,81.0,98.0,85.0,87.0
2019-12-31 23:50:00,45.0,25.0,34.0,55.0,48.0,57.0,66.0,39.0,49.0,51.0,...,84.0,70.0,71.0,86.0,147.0,79.0,62.0,73.0,70.0,70.0
2019-12-31 23:55:00,43.0,24.0,34.0,52.0,37.0,49.0,65.0,36.0,38.0,55.0,...,62.0,53.0,43.0,59.0,129.0,51.0,57.0,64.0,52.0,61.0

In [190]:
def sensor_to_fwy(df):
    return domain.set_index("ID").loc[df.columns, "Fwy"]
domain_sensor_to_fwy = sensor_to_fwy(domain_df)
domain_sensor_to_fwy

1202590    SR22-E
1214853    SR22-E
1215236    SR22-E
1202595    SR22-E
1214869    SR22-E
            ...
1212865    SR55-S
1213274    SR55-S
1212903    SR55-S
1212957    SR55-S
1203440    SR55-S
Name: Fwy, Length: 141, dtype: object

In [ ]:
def mean_flow(df, fwy):
    return df.T.groupby(fwy).apply(lambda x: np.nanmean(x.to_numpy()))

mean_flow_by_freeway = mean_flow(domain_df, domain_sensor_to_fwy)
mean_flow_by_freeway

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x176726210>

In [134]:
mean = df.mean()
mean

1202590     94.261546
1214853    111.790111
1215236    145.042064
1202595    145.469853
1214869    169.788282
              ...
1212865    282.094800
1213274    266.400685
1212903    236.473431
1212957    289.528200
1203440    291.542829
Length: 141, dtype: float64

In [88]:
c_sd = df.std(numeric_only=True)
c_sd

773869    22.693404
767541    16.069166
767542    18.387071
717447    15.929439
717446    19.380951
            ...
717592    18.331884
717595    17.053378
772168    16.377584
718141    19.206826
769373    21.244560
Length: 207, dtype: float64

In [89]:
c_max = df.max()
c_max

773869    70.0
767541    70.0
767542    70.0
717447    70.0
717446    70.0
          ...
717592    70.0
717595    70.0
772168    69.5
718141    70.0
769373    70.0
Length: 207, dtype: float64

In [90]:
RCR = df/df.max()
RCR

,773869,767541,767542,717447,717446,717445,773062,767620,737529,717816,...,772167,769372,774204,769806,717590,717592,717595,772168,718141,769373
2012-03-01 00:00:00,0.919643,0.966071,0.958929,0.878571,0.955357,0.982143,0.930357,0.958929,0.851786,0.896429,...,0.714130,0.935714,0.921429,0.948980,0.955357,0.848214,0.985714,0.852518,0.985714,0.883929
2012-03-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2012-03-01 00:30:00,0.950000,0.912500,0.969643,0.891071,0.919643,0.967857,0.930357,0.926786,0.803571,0.900000,...,0.645652,0.991071,0.850000,0.637500,0.917857,0.894643,0.935714,0.733813,0.991071,0.875000
2012-03-01 00:45:00,0.907143,0.878571,0.892857,0.830357,0.951786,0.917857,0.926786,0.950000,0.760714,0.867857,...,0.647609,0.989286,0.894643,0.841071,0.873214,0.917857,0.944643,0.730216,0.946429,0.889286
2012-03-01 01:00:00,0.873214,0.957143,0.835714,0.889286,0.948214,0.964286,0.901786,0.976786,0.800000,0.938776,...,0.663261,0.985714,0.766071,0.787755,0.989286,0.882143,0.883929,0.764388,1.000000,0.907143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-06-27 22:45:00,0.984127,0.919048,0.990476,0.798413,0.000000,0.817460,0.896825,0.912698,0.923810,0.869841,...,0.773913,0.974603,0.896825,0.893651,0.969841,0.941270,0.990476,0.949640,0.955556,0.895238
2012-06-27 23:00:00,0.948214,0.925000,0.985714,0.826786,0.000000,0.864286,0.926786,0.960714,0.839286,0.958929,...,0.815870,0.985714,0.921429,0.857143,0.960714,0.901786,0.966071,0.944245,0.955357,0.876786
2012-06-27 23:15:00,0.963265,0.959184,0.963265,0.861224,0.000000,0.783673,0.916327,0.955102,0.932653,0.940816,...,0.840745,0.944898,0.910204,0.857143,0.981633,0.887755,0.989796,0.959918,0.969388,0.869388
2012-06-27 23:30:00,0.898214,0.941071,0.975000,0.896429,0.000000,0.821429,0.908929,0.892857,0.826786,0.941071,...,0.817826,0.991071,0.921429,0.889286,0.925000,0.891071,0.985714,0.926259,0.967857,0.862500
2012-06-27 23:45:00,0.957143,0.852381,0.993651,0.871429,0.000000,0.639683,0.917460,0.911111,0.853968,0.823810,...,0.803478,0.969841,0.919048,0.814286,0.942857,0.895238,0.980952,0.911271,0.963492,0.874603

In [91]:
df.index.dtype

dtype('<M8[ns]')

In [92]:
profile = pd.DataFrame(columns = df.columns)
for i in range(0,24):
    profile.loc[i] = df.loc[df.index.hour == i].mean()
profile

,773869,767541,767542,717447,717446,717445,773062,767620,737529,717816,...,772167,769372,774204,769806,717590,717592,717595,772168,718141,769373
0,54.402784,58.899135,59.833922,54.752411,57.467690,51.155307,57.891727,57.733497,54.990449,58.344353,...,41.923384,60.829885,53.550972,54.872552,57.504110,54.931699,60.079453,57.303016,59.887247,55.123953
1,56.000108,60.462182,61.311919,56.809890,60.371513,52.562580,60.098961,59.327418,54.794354,58.234049,...,41.125595,62.459854,53.198970,54.837849,57.848468,55.908984,60.814164,58.362324,60.370896,56.703431
2,54.482799,59.588340,60.535748,55.117260,60.112668,51.739179,59.595692,58.852207,52.671596,56.423047,...,38.330626,60.804146,51.696933,53.439869,55.064978,54.913042,59.865331,57.523107,58.534876,55.504410
3,53.302668,58.405776,60.480721,53.016159,59.137356,51.255506,58.577716,58.153440,52.457773,56.779119,...,35.094428,59.099767,47.903032,52.743001,53.300734,53.179901,58.388167,57.241364,56.449158,55.050868
4,54.511905,57.384806,61.870995,53.365304,59.933119,52.673467,59.193687,56.978945,55.131709,59.810267,...,36.251514,59.627042,48.267414,54.967271,55.192250,53.763057,59.444696,59.408588,57.741506,57.558812
5,56.323488,57.445599,62.246757,53.489054,60.098298,55.125199,59.730109,57.523872,55.309624,59.455758,...,40.573959,61.139022,51.193527,57.182569,57.566785,54.414332,60.243193,59.709971,58.382920,58.844359
6,57.395041,58.197271,59.830624,50.685146,54.163532,53.581618,60.108847,57.595685,44.061698,36.275579,...,42.005005,61.341382,53.069283,59.222946,58.858313,55.784853,61.204961,52.078024,59.683227,54.148163
7,58.580837,59.650135,41.709217,48.404062,45.164337,49.959584,59.930418,57.658901,46.775452,25.666404,...,38.732268,61.981313,52.837234,60.918731,59.276269,57.570999,62.455120,46.544910,60.288515,53.309424
8,57.200023,59.478033,38.485557,48.227154,41.614477,50.253208,58.941970,57.502238,41.616664,25.185860,...,36.256943,61.989212,52.735119,60.641499,47.760938,57.603489,61.661129,44.268744,59.464175,45.913410
9,56.459344,59.246459,54.235045,46.288348,39.843467,48.693591,57.214124,57.676992,46.276999,26.467733,...,39.387603,60.990157,52.054134,59.935765,52.491875,55.780960,60.804158,45.589590,59.695704,48.696430
10,57.057706,59.592608,61.024822,46.047202,38.277269,48.680835,56.102099,56.542947,53.400240,32.475535,...,39.543338,60.596322,53.084138,59.812336,59.267119,55.709271,61.114883,48.380702,59.682010,48.548982
11,57.093946,61.299495,63.543883,48.695915,36.943425,52.997340,56.925851,56.433247,57.780120,43.005935,...,38.444525,62.306722,55.710512,60.816189,60.159530,56.005766,62.936809,52.801011,60.720934,48.482555
12,57.514848,61.588415,63.550508,48.786619,35.603225,53.892315,55.816477,54.559732,58.127664,50.129127,...,36.979709,62.086589,54.703601,61.095742,60.477744,56.100536,62.779366,53.590211,60.561333,48.934545
13,57.257534,61.035832,62.835301,46.883777,33.738449,52.143819,54.179734,53.443328,58.466168,51.822320,...,35.809709,61.494036,53.466561,60.486795,60.487512,56.249971,62.387868,53.053210,58.864710,50.270032
14,57.722693,61.321241,63.235263,46.825008,35.171407,52.742419,42.289832,52.960921,58.699820,56.348561,...,34.207090,61.773273,52.869477,61.229087,61.595841,56.709234,62.414951,51.854498,56.685987,50.716374
15,56.232527,62.651412,64.686101,45.816403,34.974195,51.194291,38.612272,53.318204,60.996015,62.440750,...,30.579100,56.186301,46.937073,63.531213,63.223494,58.525115,64.520829,51.975945,53.500514,49.349356
16,50.726787,61.939309,64.946178,40.867985,32.597597,45.985344,36.767319,53.155366,62.513402,64.773868,...,27.570707,38.047765,39.916783,64.135767,63.735966,59.280033,65.244389,52.584234,52.725186,39.858156
17,37.380765,59.627531,64.359423,38.199640,30.916267,42.334128,38.767635,53.726503,62.151230,64.184545,...,26.368620,31.744986,32.703504,63.898726,63.328208,58.749733,64.769999,51.460707,52.141230,34.726492
18,33.008533,59.455386,63.819019,41.515656,38.466057,45.266257,45.398230,56.355396,61.831841,62.433063,...,27.060999,35.519142,34.792499,62.933380,62.827702,58.843379,64.017620,53.362616,51.935198,39.889472
19,50.964698,62.432419,65.747880,48.360604,42.173028,49.603094,55.604929,60.081683,62.925318,63.667399,...,36.411688,55.933492,51.744728,63.397697,63.533418,59.929042,65.461300,59.433728,60.740285,48.531028
20,59.544455,63.386642,66.200293,53.829832,47.103562,53.688270,58.517349,61.626951,62.442915,64.239375,...,46.009942,65.608889,60.508157,62.901704,63.695591,60.001488,65.884495,62.223925,64.632290,56.337531
21,59.843886,61.967237,64.346968,53.306172,50.323300,52.312671,57.671682,60.313375,60.715724,63.316878,...,46.276836,64.807423,58.921444,60.958108,62.766945,58.320873,64.462712,61.278103,62.743793,57.735557
22,58.891646,61.913031,63.982125,52.658274,53.102509,51.205236,57.961505,60.556052,59.996905,63.170744,...,45.841995,64.170541,58.109862,60.025903,62.079142,58.224383,63.837309,61.284652,63.085365,57.248158
23,58.018692,62.068011,63.567856,55.115435,56.452393,52.198676,59.598384,60.616733,59.558907,62.958969,...,45.419143,63.437266,58.047822,58.916379,61.727184,58.078027,63.620574,60.922652,63.121720,56.695605

In [100]:
from datetime import datetime, timedelta

def recent_twelve_readings(time, min = 15, freq = 12):
    span = timedelta(minutes = min * freq-1)
    window = df.loc[time - span : time]
    return window

window = recent_twelve_readings(pd.Timestamp("2012-03-10 04:15:00"))
window

,773869,767541,767542,717447,717446,717445,773062,767620,737529,717816,...,772167,769372,774204,769806,717590,717592,717595,772168,718141,769373
2012-03-10 01:30:00,63.375000,66.750000,63.625000,60.625000,68.875000,67.125000,67.125000,65.750000,59.000000,60.375000,...,43.500000,69.000000,0.0,48.375000,61.375000,63.625000,68.625000,61.625000,67.000000,62.125000
2012-03-10 01:45:00,67.625000,66.750000,67.625000,60.750000,64.500000,56.571429,66.250000,64.375000,65.000000,67.750000,...,45.000000,68.750000,0.0,61.000000,69.500000,64.625000,64.250000,62.125000,68.750000,61.125000
2012-03-10 02:00:00,66.000000,66.500000,67.750000,60.000000,66.250000,64.571429,65.625000,66.625000,61.750000,62.250000,...,41.250000,68.571429,0.0,57.625000,69.875000,66.375000,67.750000,60.125000,68.625000,63.285714
2012-03-10 02:15:00,65.000000,65.875000,64.625000,63.500000,66.375000,68.875000,64.875000,65.875000,53.250000,69.428571,...,47.625000,68.500000,0.0,61.250000,62.875000,62.125000,67.500000,62.250000,69.500000,63.125000
2012-03-10 02:30:00,64.222222,67.222222,68.444444,60.333333,67.333333,66.555556,65.444444,66.111111,61.777778,61.666667,...,44.333333,65.666667,0.0,66.111111,55.222222,62.888889,66.444444,63.333333,67.444444,60.888889
2012-03-10 02:45:00,59.666667,66.888889,68.000000,63.111111,67.444444,67.111111,67.555556,66.333333,57.000000,66.444444,...,44.222222,61.333333,0.0,50.250000,62.111111,59.444444,65.888889,60.222222,67.000000,62.333333
2012-03-10 03:00:00,65.500000,65.750000,69.500000,60.875000,68.625000,67.500000,62.875000,61.375000,63.125000,67.375000,...,46.714286,65.250000,0.0,56.750000,63.125000,67.625000,68.125000,65.142857,69.750000,62.875000
2012-03-10 03:15:00,62.875000,62.000000,67.375000,62.625000,68.375000,66.000000,67.000000,63.250000,62.000000,66.857143,...,40.000000,67.000000,0.0,54.375000,66.500000,61.000000,65.375000,68.125000,65.250000,61.250000
2012-03-10 03:30:00,60.375000,65.125000,64.750000,57.000000,66.625000,64.125000,66.375000,67.375000,62.750000,65.500000,...,45.500000,66.625000,0.0,57.750000,63.750000,65.000000,68.875000,65.250000,65.750000,58.375000
2012-03-10 03:45:00,53.250000,68.000000,68.375000,61.125000,64.625000,66.125000,64.750000,63.750000,64.500000,67.500000,...,40.875000,65.125000,0.0,59.000000,66.625000,61.250000,68.000000,64.250000,68.500000,61.750000
2012-03-10 04:00:00,62.200000,66.200000,62.600000,61.400000,67.800000,59.400000,63.600000,62.400000,47.800000,68.800000,...,39.800000,59.200000,0.0,60.400000,57.000000,69.200000,68.400000,66.400000,68.200000,58.800000
2012-03-10 04:15:00,60.000000,66.125000,68.000000,56.875000,63.750000,62.000000,62.625000,68.125000,58.250000,66.375000,...,40.125000,64.375000,0.0,59.375000,60.375000,58.625000,65.125000,65.000000,65.000000,63.125000

In [94]:
row, col = window.shape
row

2

Timestamp('2012-03-10 04:15:00')

In [132]:
from datetime import datetime, timedelta

def short_term_trend(readings, freq = 4):
    subwindow = readings.iloc[-freq:]
    trends = pd.DataFrame(columns= df.columns)
    old_value = subwindow.iloc[0]
    new_value = subwindow.iloc[-1]
    trends = (new_value - old_value)/ (freq-1)
    return subwindow, trends

subwindow, trends = short_term_trend(window)

In [133]:
subwindow

,773869,767541,767542,717447,717446,717445,773062,767620,737529,717816,...,772167,769372,774204,769806,717590,717592,717595,772168,718141,769373
2012-03-10 03:30:00,60.375,65.125,64.750,57.000,66.625,64.125,66.375,67.375,62.75,65.500,...,45.500,66.625,0.0,57.750,63.750,65.000,68.875,65.25,65.75,58.375
2012-03-10 03:45:00,53.250,68.000,68.375,61.125,64.625,66.125,64.750,63.750,64.50,67.500,...,40.875,65.125,0.0,59.000,66.625,61.250,68.000,64.25,68.50,61.750
2012-03-10 04:00:00,62.200,66.200,62.600,61.400,67.800,59.400,63.600,62.400,47.80,68.800,...,39.800,59.200,0.0,60.400,57.000,69.200,68.400,66.40,68.20,58.800
2012-03-10 04:15:00,60.000,66.125,68.000,56.875,63.750,62.000,62.625,68.125,58.25,66.375,...,40.125,64.375,0.0,59.375,60.375,58.625,65.125,65.00,65.00,63.125

In [134]:
trends

773869   -0.125000
767541    0.333333
767542    1.083333
717447   -0.041667
717446   -0.958333
            ...
717592   -2.125000
717595   -1.250000
772168   -0.083333
718141   -0.250000
769373    1.583333
Length: 207, dtype: float64